name: medical_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  get: ^4.7.2
  font_awesome_flutter: ^10.8.0
  lottie: ^3.3.1
  animated_toggle_switch: ^0.8.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.7
  get_storage: ^2.1.1
  intl: ^0.18.0
  flutter_otp_text_field: ^1.5.1+1
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  google_sign_in: ^6.3.0
  http: ^1.3.0
  connectivity_plus: ^6.1.3
  awesome_snackbar_content: ^0.1.1
  internet_connection_checker: ^3.0.1
  get_it: ^8.0.3
  provider: ^6.0.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  cached_network_image: ^3.4.1
  device_info_plus: ^11.3.3
  permission_handler: ^12.0.0+1
  firebase_storage: ^12.4.5
#  permission_handler: ^11.3.1
#  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/